# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8081
  port: 8082
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      max: 800 # tomcat最大线程数，默认为200
      min-spare: 30 # Tomcat启动初始化的线程数，默认值25

# Spring配置
spring:
  profiles:
    active: druid


# 日志配置
logging:
  level:
    com.zzx.ruoyi: debug
    org.springframework: warn

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql  # 配置使用哪种数据库语言，不配置的话pageHelper也会自动检测
  supportMethodsArguments: true  # 支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  params: count=countSql # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  reasonable: false # 配置分页参数合理化功能，默认是false。 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页； 禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据。
